[profile.default]
# Default timeout for local development
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
fail-fast = false
slow-timeout = { period = "120s", terminate-after = 60 }
